Allow providing config values only via environment
kkyr/fig pull request #9
Opened 2021-11-13 01:14 UTC by rsjethani

The changes add a new `NoFile` option and the new
`fig.ignoreFile` field.

Giving this option to `Load()` will:
- Disable the default file lookup process
- The `File` and `Dir` option still work as before but
  become ineffective in the presence of `NoFile` option.

Signed-off-by: Ravi Shekhar Jethani <rsjethani@gmail.com>

2021-11-13 01:16 UTC, rsjethani commented
Addresses #5

2021-11-14 19:32 UTC, kkyr commented
Thanks for the PR!

I'll allocate some time to go over it in the next few days.

2021-11-15 21:36 UTC, kkyr requested changes
`doc.go` should also be updated:
1. Explanation of `IgnoreFile` under its own heading
2. Update wording under `Environment` heading accordingly, since config file is no longer always mandatory.

2021-11-15 21:36 UTC, kkyr commented on fig.go
> +
Unnecessary newline

2021-11-15 21:36 UTC, kkyr commented on fig_test.go
> +	t.Run("NOFILE", func(t *testing.T) {
No need to run a subtest here.

2021-11-15 21:36 UTC, kkyr commented on option.go
> +func NoFile() Option {
I believe `IgnoreFile` would be a more descriptive name here, since we're telling `fig` to actually ignore the file (even if it exists).

2021-11-15 21:36 UTC, kkyr commented on option.go
> +// NoFile returns an option which disables any file lookup
Period at end of line.

2021-11-15 21:36 UTC, kkyr commented on option.go
> +// the environment. But if `NoFile` option is also given then config file is omitted.
We could simplify this by instead saying something along the lines of "Values loaded from the environment overwrite values loaded by the config file (if any)."

2021-12-10 21:48 UTC, rsj-ioki commented
Thanks for the review, changes added

2021-12-26 20:59 UTC, kkyr commented
Please also add a description to `doc.go` as described in one of my comments above.

2021-12-27 01:32 UTC, rsjethani commented
updated docs

2022-01-03 22:02 UTC, merged